# Generated by Django 5.0.1 on 2024-01-09 22:09

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1024)),
                ('creating_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('starting_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ending_at', models.DateTimeField(default=datetime.datetime(2024, 2, 8, 22, 9, 9, 598883, tzinfo=datetime.timezone.utc))),
                ('is_available', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Survey',
                'verbose_name_plural': 'Surveys',
            },
        ),
    ]
