# Generated by Django 5.0.1 on 2024-01-21 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_alter_response_respondent_alter_survey_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='number_of_respondent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='survey',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 18, 17, 27, 18, 414937, tzinfo=datetime.timezone.utc)),
        ),
    ]
