# Generated by Django 5.0.1 on 2024-01-21 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_alter_survey_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='number_of_respondent',
            new_name='number_of_responses',
        ),
        migrations.AlterField(
            model_name='survey',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 18, 17, 30, 2, 42824, tzinfo=datetime.timezone.utc)),
        ),
    ]
