# Generated by Django 5.0.1 on 2024-01-21 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_rename_number_of_respondent_survey_number_of_responses_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='start_date',
            new_name='starting_date',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='end_date',
        ),
        migrations.AddField(
            model_name='survey',
            name='ending_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 18, 17, 30, 42, 564905, tzinfo=datetime.timezone.utc)),
        ),
    ]
