# Generated by Django 5.0.1 on 2024-01-21 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_rename_start_date_survey_starting_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='ending_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 18, 17, 31, 8, 215010, tzinfo=datetime.timezone.utc)),
        ),
    ]
