# Generated by Django 5.0.1 on 2024-01-22 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_alter_survey_ending_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='creating_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='ending_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 18, 12, 18, 690546, tzinfo=datetime.timezone.utc)),
        ),
    ]
