# Generated by Django 5.0.1 on 2024-01-27 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_alter_survey_creating_date_alter_survey_ending_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Respondent',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='survey',
            name='ending_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 24, 17, 1, 58, 577711, tzinfo=datetime.timezone.utc)),
        ),
    ]
