# Generated by Django 5.0.1 on 2024-01-29 17:58

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_alter_survey_ending_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='ending_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 26, 17, 58, 31, 768008, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='SpentTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(default=datetime.time)),
                ('end_time', models.TimeField(default=datetime.time)),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey')),
            ],
            options={
                'verbose_name': 'SpentTime',
                'verbose_name_plural': 'SpentTime',
            },
        ),
    ]
